name: CI Matrix Workflow Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  read-from-list:
    runs-on: ubuntu-latest
    outputs:
      output-list: ${{ steps.read-list-step.outputs.list }}
    steps:
      - name: Check out the list file
        uses: actions/checkout@v3
      - name: Read from list file
        id: read-list-step
        run: echo "list=$(python3 read_list.py)" >> $GITHUB_OUTPUT
  debug-job:
    runs-on: ubuntu-latest
    needs: read-from-list
    steps:
      - name: Debug
        run: echo ${{ needs.read-from-list.outputs.list }}
      
  test-operation:
    runs-on: ubuntu-latest
    needs: read-from-list
    strategy:
      matrix:
        run: echo ${{ needs.read-from-list.outputs.list }}
    steps:
    - run: echo Run ${{ matrix.run }}
